-- Custom SQL migration file, put your code below! --

-- Issue #29 — full-text search. FTS5 virtual tables aren't representable
-- as a drizzle-orm sqliteTable, so this is hand-authored rather than
-- generated by `pnpm db:generate`'s drizzle-kit diff — the SQL mirrors
-- @thebes/cadmus/cms's collectionSearchTableSQL(pagesCollection) exactly
-- (see app/cadmea.config.ts's `search: { fields: ["title"] }`). Kept in
-- sync by createLocalApi on every pages create/update/delete/publish —
-- nothing else needs to touch this table directly.
CREATE VIRTUAL TABLE IF NOT EXISTS "pages_fts" USING fts5("title");
