// Generated by @bowenlabs/cadmus/cms — do not hand-edit.
// Source: this app's CmsConfig (see defineCmsConfig).
import type { JsonValue } from "@bowenlabs/cadmus/cms";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const pages = sqliteTable("pages", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  title: text("title").notNull(),
  slug: text("slug").notNull().unique(),
  status: text("status", { enum: ["draft", "published"] })
    .notNull()
    .default("draft"),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(
    () => new Date(),
  ),
  blocks: text("blocks", { mode: "json" }).$type<JsonValue>(),
  metaTitle: text("meta_title"),
  metaDescription: text("meta_description"),
  ogImage: text("og_image"),
  publishedVersionId: integer("published_version_id"),
});

export const pages_versions = sqliteTable("pages_versions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  parentId: integer("parent_id").notNull(),
  versionData: text("version_data", { mode: "json" })
    .$type<JsonValue>()
    .notNull(),
  status: text("status", { enum: ["draft", "published"] }).notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).$defaultFn(
    () => new Date(),
  ),
});
